{{- if not .Values.ssh.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "conduit.fullname" . }}
  labels:
    {{- include "conduit.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.ssh.secretKey }}: {{ .Values.ssh.password | quote }}
{{- end }}